### ISSUE TITLE
Exclude self link from resource

### ISSUE THREAD

**Issue by danherd** [cloudcreativity/laravel-json-api#108]
Simple one (I hope).

How do I hide the links section if it isn't required? For example:

```
GET https://app.dev/api/locums/F00BBDCF-62D5-4C2D-ADFB-B62615D64271/currency

{
    "data": {
        "type": "currencies",
        "id": "GBP",
        "attributes": {
            "name": "British Pound Sterling"
        },
        "links": {
            "self": "https://loc8um.dev/api/currencies/GBP"
        }
    }
}
```

The 'self' link there is not (and will not be) available, so I'd like to not include the 'links' section in that response.

Cheers,

Dan

**Comment by lindyhopchris** [comment]
Add this to your currencies schema:

```php
    public function getResourceLinks($resource)
    {
        return [];
    }
```

**Comment by danherd** [comment]
Perfect - thanks!

**Comment by saddamshahzadnxb** [comment]
I using version 6. I added this in my Schema and it won't remove self links

**Comment by lindyhopchris** [comment]
@saddamshahzadnxb can you confirm you're using `cloudcreativity/laravel-json-api` or `laravel-json-api/laravel`?

**Comment by saddamshahzadnxb** [comment]
"cloudcreativity/laravel-json-api": "^6.1"

**Comment by lindyhopchris** [comment]
Yeah sorry this package is a bit old, but looking here:
https://github.com/cloudcreativity/laravel-json-api/blob/86e9dbad5df8f077f75f7803fa70e6800d1f113e/src/Schema/Schema.php#L122

You need to return `false` for the `self` link.

**Comment by saddamshahzadnxb** [comment]
How should I do it globally, I want to disable all resource links

**Comment by lindyhopchris** [comment]
Would suggest you define a schema class that returns that from `getResourceLinks()` and then extend that for all your schemas.

**Comment by saddamshahzadnxb** [comment]
We are extending all our Schema classes from an AbstractSchema class which looks like this


```
<?php

namespace App\JsonApi;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use CloudCreativity\LaravelJsonApi\Schema\SchemaProvider;

abstract class AbstractSchema extends SchemaProvider
{
    public static $append_timestamps = true;

    protected static $soft_delete = true;

    /**
     * @var array
     */
    protected $relationships = [];

    /**
     * @var array An optional array of resources for endpoints that return multiple resource types using the same schema
     */
    protected array $explicit_field_resource_types = [];

    /**
     * @param Model $resource
     *
     * @return string
     */
    public function getId(object $resource) : string
    {
        return (string)$resource->getRouteKey();
    }

    public function getExplicitlyRequestedFields(): array
    {
        if (count($this->explicit_field_resource_types) === 0) {
            $this->explicit_field_resource_types[] = $this->resourceType;
        }

        return Collection::make($this->explicit_field_resource_types)
            ->map(function (string $resource_type) {
                return explode(',', request()->get('fields')[$resource_type] ?? null);
            })
            ->filter()
            ->flatten()
            ->unique()
            ->toArray();
    }

    /**
     * @param Model $resource
     *
     * @return array
     */
    public function getAttributes(object $resource) :array
    {
        $fields = $this->getExplicitlyRequestedFields();

        $raw_demand_attributes = $this->getOnDemandAttributes($resource);
        $on_demand_attributes  = [];

        foreach ($raw_demand_attributes as $attribute => $function) {
            if (in_array($attribute, $fields, true)) {
                $on_demand_attributes[$attribute] = $function($resource);
            }
        }

        $raw_relationship_count_attributes = $this->getRelationshipCountAttributes($resource);
        $relationship_count_attributes     = [];

        foreach ($raw_relationship_count_attributes as $attribute => $function) {
            if (in_array($attribute, $fields, true)) {
                $relationship_count_attributes[$attribute] = $function($resource);
            }
        }

        if (! static::$append_timestamps) {
            return array_merge(
                $on_demand_attributes,
                $relationship_count_attributes,
                $this->formatAttributes($resource)
            );
        }

        return array_merge(
            $on_demand_attributes,
            $relationship_count_attributes,
            $this->formatAttributes($resource),
            $this->appendTimestamps($resource, static::$soft_delete)
        );
    }

    protected function formatAttributes($resource)
    {
        return [];
    }

    public function getOnDemandAttributes($resource): array
    {
        return [];
    }

    public function getRelationshipCountAttributes($resource): array
    {
        return [];
    }

    public function changeCase($array)
    {
        $data = new Collection($array);

        return $data->camelCaseKeys()->toArray();
    }

    /**
     * @param Model $resource
     * @param bool  $isPrimary
     * @param array $includedRelationships
     *
     * @return array
     */
    public function getRelationships(object $resource, $isPrimary, array $includedRelationships) :array
    {
        $relationships = [];
        foreach ($this->relationships as $relationship) {
            if (isset($includedRelationships[$relationship])) {
                $relationships[$relationship] = [
                    self::SHOW_SELF    => false,
                    self::SHOW_RELATED => false,
                    self::SHOW_DATA    => isset($includedRelationships[$relationship]),
                    self::DATA         => function () use ($resource, $relationship) {
                        $relationship_camel = Str::camel($relationship);

                        return $resource->{$relationship_camel};
                    },
                ];
            }
        }

        return $relationships;
    }

    /**
     * @param Carbon|null $date
     *
     * @return string|null
     */
    protected function getOrNullDate($date, $format = 'c')
    {
        return $date && $date instanceof \DateTimeInterface ? $date->format($format) : null;
    }

    /**
     * @param Model $resource
     * @param bool  $softDelete
     *
     * @return array
     */
    protected function appendTimestamps(Model $resource, $softDelete = false)
    {
        return [
            'created_at' => $this->getOrNullDate($resource->created_at),
            'updated_at' => $this->getOrNullDate($resource->updated_at),
            'deleted_at' => $this->getOrNullDate($resource->deleted_at),
        ];
    }
}
```

**Comment by saddamshahzadnxb** [comment]
I added below is my AbstractShema class but no effect

```
public function getResourceLinks($resource): iterable
    {
        return [];
    }
```

**Comment by lindyhopchris** [comment]
As per the linked code I sent in a message above, try:

```
public function getResourceLinks($resource): iterable
{
    return ['self' => false];
}

```

**Comment by saddamshahzadnxb** [comment]
It is throwing error like this

```
assert($link instanceof LinkInterface) {"userId":85750,"exception":"[object] (AssertionError(code: 1): assert($link instanceof LinkInterface) at /var/www/html/vendor/laravel-json-api/neomerx-json-api/src/Parser/IdentifierAndResource.php:287)
[stacktrace]
#0 /var/www/html/vendor/laravel-json-api/neomerx-json-api/src/Parser/IdentifierAndResource.php(287): assert(false, 'assert($link in...')
#1 /var/www/html/vendor/laravel-json-api/neomerx-json-api/src/Parser/IdentifierAndResource.php(239): Neomerx\\JsonApi\\Parser\\IdentifierAndResource->cacheLinks()
#2 /var/www/html/vendor/laravel-json-api/neomerx-json-api/src/Representation/DocumentWriter.php(289): Neomerx\\JsonApi\\Parser\\IdentifierAndResource->hasLinks()
#3 /var/www/html/vendor/laravel-json-api/neomerx-json-api/src/Representation/DocumentWriter.php(68): Neomerx\\JsonApi\\Representation\\DocumentWriter->getResourceRepresentation(Object(Neomerx\\JsonApi\\Parser\\IdentifierAndResource), Object(Neomerx\\JsonApi\\Representation\\FieldSetFilter))
#4 /var/www/html/vendor/laravel-json-api/neomerx-json-api/src/Encoder/Encoder.php(198): Neomerx\\JsonApi\\Representation\\DocumentWriter->addResourceToData(Object(Neomerx\\JsonApi\\Parser\\IdentifierAndResource), Object(Neomerx\\JsonApi\\Representation\\FieldSetFilter))
#5 /var/www/html/vendor/cloudcreativity/laravel-json-api/src/Encoder/Encoder.php(184): Neomerx\\JsonApi\\Encoder\\Encoder->encodeDataToArray(Object(Illuminate\\Pagination\\LengthAwarePaginator))
#6 /var/www/html/vendor/laravel-json-api/neomerx-json-api/src/Encoder/Encoder.php(106): CloudCreativity\\LaravelJsonApi\\Encoder\\Encoder->encodeDataToArray(Object(Illuminate\\Pagination\\LengthAwarePaginator))
#7 /var/www/html/vendor/laravel-json-api/neomerx-json-api/src/Http/BaseResponses.php(64): Neomerx\\JsonApi\\Encoder\\Encoder->encodeData(Object(Illuminate\\Pagination\\LengthAwarePaginator))
#8 /var/www/html/src/Custom/cloudcreativity/LaravelJsonApi/Responses/Responses.php(260): Neomerx\\JsonApi\\Http\\BaseResponses->getContentResponse(Object(Illuminate\\Pagination\\LengthAwarePaginator), 200, Array)
#9 /var/www/html/src/Custom/cloudcreativity/LaravelJsonApi/Responses/Responses.php(231): Custom\\cloudcreativity\\LaravelJsonApi\\Responses\\Responses->getContentResponseBackwardsCompat(Object(Illuminate\\Pagination\\LengthAwarePaginator), 200, Array, Array, Array)
#10 /var/www/html/src/App/Http/Controllers/Api/AbstractJsonApiController.php(71): Custom\\cloudcreativity\\LaravelJsonApi\\Responses\\Responses->content(Object(CloudCreativity\\LaravelJsonApi\\Pagination\\Page), Array, Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\AbstractJsonApiController->index(Object(CloudCreativity\\LaravelJsonApi\\Store\\Store), Object(CloudCreativity\\LaravelJsonApi\\Http\\Requests\\FetchResources), 'companies')
```

**Comment by lindyhopchris** [comment]
So that's a bug. You'll need to submit a PR that unsets the `self` link if the value is `false` after this `if` block:
https://github.com/cloudcreativity/laravel-json-api/blob/86e9dbad5df8f077f75f7803fa70e6800d1f113e/src/Schema/Schema.php#L122
