### ISSUE TITLE
Selectively disable middleware and/or authorizer and/or relationships for a particular route

### ISSUE THREAD

**Issue by itwebdeveloper** [cloudcreativity/laravel-json-api#331]
Hi,
is it possible to selectively disable middleware and/or authorizer and/or relationships for a particular route?
Normally I am using passport password access token as bearer for authenticating the user with access to a resource but for the user creation I would like to skip any authentication and let the users to be created by anyone. 
So I wrote the following `/routes/api.php`:

```
<?php

use CloudCreativity\LaravelJsonApi\Facades\JsonApi;
use CloudCreativity\LaravelJsonApi\Routing\RouteRegistrar;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

JsonApi::register('v1')->withNamespace('Api')->routes(function (RouteRegistrar $api, $router) {
    $api->get('users', 'UsersController@index')->middleware('auth:api')->authorizer('default')->relationships(function ($relations) {
        $relations->hasMany('posts');
    });
    $api->post('users', 'UsersController@create')->relationships(function ($relations) {
        $relations->hasMany('posts');
    });
    $api->get('/users/{record}', 'UsersController@read')->middleware('auth:api')->authorizer('default')->relationships(function ($relations) {
        $relations->hasMany('posts');
    });
    $api->patch('/users/{record}', 'UsersController@update')->middleware('auth:api')->authorizer('default')->relationships(function ($relations) {
        $relations->hasMany('posts');
    });
    $api->delete('/users/{record}', 'UsersController@delete')->middleware('auth:api')->authorizer('default')->relationships(function ($relations) {
        $relations->hasMany('posts');
    });
});
```

but I receive the following error:

```
[2019-03-23 10:48:16] local.ERROR: Method Illuminate\Routing\Route::authorizer does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Routing\\Route::authorizer does not exist. at /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:100)
[stacktrace]
#0 /home/vagrant/code/example-api/routes/api.php(18): Illuminate\\Routing\\Route->__call('authorizer', Array)
#1 /home/vagrant/code/example-api/vendor/cloudcreativity/laravel-json-api/src/Routing/ApiRegistration.php(154): App\\Providers\\RouteServiceProvider->{closure}(Object(CloudCreativity\\LaravelJsonApi\\Routing\\RouteRegistrar), Object(Illuminate\\Routing\\Router))
#2 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(413): CloudCreativity\\LaravelJsonApi\\Routing\\ApiRegistration->CloudCreativity\\LaravelJsonApi\\Routing\\{closure}(Object(Illuminate\\Routing\\Router))
#3 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(373): Illuminate\\Routing\\Router->loadRoutes(Object(Closure))
#4 /home/vagrant/code/example-api/vendor/cloudcreativity/laravel-json-api/src/Routing/ApiRegistration.php(156): Illuminate\\Routing\\Router->group(Array, Object(Closure))
#5 /home/vagrant/code/example-api/routes/api.php(45): CloudCreativity\\LaravelJsonApi\\Routing\\ApiRegistration->routes(Object(Closure))
#6 /home/vagrant/code/example-api/app/Providers/RouteServiceProvider.php(72): require('/home/vagrant/c...')
#7 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(413): App\\Providers\\RouteServiceProvider->App\\Providers\\{closure}(Object(Illuminate\\Routing\\Router))
#8 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(373): Illuminate\\Routing\\Router->loadRoutes(Object(Closure))
#9 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Routing\\Router->group(Array, Object(Closure))
#10 /home/vagrant/code/example-api/app/Providers/RouteServiceProvider.php(73): Illuminate\\Support\\Facades\\Facade::__callStatic('group', Array)
#11 /home/vagrant/code/example-api/app/Providers/RouteServiceProvider.php(38): App\\Providers\\RouteServiceProvider->mapApiRoutes()
#12 [internal function]: App\\Providers\\RouteServiceProvider->map()
#13 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#14 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#16 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#17 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(77): Illuminate\\Container\\Container->call(Array)
#18 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(36): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->loadRoutes()
#19 /home/vagrant/code/example-api/app/Providers/RouteServiceProvider.php(28): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->boot()
#20 [internal function]: App\\Providers\\RouteServiceProvider->boot()
#21 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(819): Illuminate\\Container\\Container->call(Array)
#26 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(802): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\RouteServiceProvider))
#27 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\RouteServiceProvider), 25)
#28 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(803): array_walk(Array, Object(Closure))
#29 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#30 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(211): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#31 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#32 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#33 /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#34 /home/vagrant/code/example-api/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#35 {main}
"} 
```

If I move the authorizer in the registration, e.g.:

```
JsonApi::register('v1')->withNamespace('Api')->authorizer('default')->routes(function (RouteRegistrar $api, $router) {
    $api->get('users', 'UsersController@index')->middleware('auth:api')->relationships(function ($relations) {
        $relations->hasMany('posts');
    });
    ...
});
```

I get the following error:

```
[2019-03-23 13:04:38] local.ERROR: Method Illuminate\Routing\Route::relationships does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Routing\\Route::relationships does not exist. at /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:100)
```

I also tried with the following combinations:

1.
    ```
    JsonApi::register('v1')->withNamespace('Api')->routes(function (RouteRegistrar $api, $router) {
        $api->resource('users')->controller()->routes(function ($users) {
            $users->post('users', 'create');
            $users->middleware('auth:api')->authorizer('default')->get('users', 'index');
            $users->middleware('auth:api')->authorizer('default')->get('/users/{record}', 'read');
            $users->middleware('auth:api')->authorizer('default')->patch('/users/{record}', 'update');
            $users->middleware('auth:api')->authorizer('default')->delete('/users/{record}', 'delete');
        })->relationships(function ($relations) {
            $relations->hasMany('posts');
        });
    });
    ```
    but I get:

    ```
    [2019-03-23 13:04:38] local.ERROR: Method Illuminate\Routing\Route::relationships does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Routing\\Route::relationships does not exist. at /home/vagrant/code/example-api/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:100)
    ```

2.
    ```
    JsonApi::register('v1')->withNamespace('Api')->authorizer('default')->routes(function (RouteRegistrar $api, $router) {
        $api->resource('users')->controller()->routes(function ($users) {
            $users->post('users', 'create');
            $users->middleware('auth:api')->get('users', 'index');
            $users->middleware('auth:api')->get('/users/{record}', 'read');
            $users->middleware('auth:api')->patch('/users/{record}', 'update');
            $users->middleware('auth:api')->delete('/users/{record}', 'delete');
        })->relationships(function ($relations) {
            $relations->hasMany('lists');
        });
    });
    ```
    but while all works good for `index`, `read`, `update` and `delete` I receive 

    ```
    {
        "errors": [
            {
                "status": "401",
                "title": "Unauthenticated"
            }
        ]
    }
    ```
    when sending a `create` (POST) request without including the access token in the header.

3. 
    ```
    JsonApi::register('v1')->withNamespace('Api')->authorizer('default')->routes(function (RouteRegistrar $api, $router) {
        $api->resource('users')->controller()->routes(function ($users) {
            $users->middleware('guest')->post('users', 'create');
            $users->middleware('auth:api')->get('users', 'index');
            $users->middleware('auth:api')->get('/users/{record}', 'read');
            $users->middleware('auth:api')->patch('/users/{record}', 'update');
            $users->middleware('auth:api')->delete('/users/{record}', 'delete');
        })->relationships(function ($relations) {
            $relations->hasMany('lists');
        });
    });
    ```
    but while all works good for `index`, `read`, `update` and `delete` I receive 

    ```
    {
        "errors": [
            {
                "status": "401",
                "title": "Unauthenticated"
            }
        ]
    }
    ```
    when sending a `create` (POST) request without including the access token in the header.

**Comment by lindyhopchris** [comment]
Hi,

You don't need to selectively disable anything. Just overloads the `create` method on your authorizer and do nothing in it - i.e. don't deny the request.

**Comment by itwebdeveloper** [comment]
Hi @lindyhopchris , thanks for your response.
I reverted the `routes/api.php` to the original version:

```
JsonApi::register('v1')->middleware('auth:api')->authorizer('default')->withNamespace('Api')->routes(function (RouteRegistrar $api, $router) {
    $api->resource('users')->relationships(function ($relations) {
        $relations->hasMany('posts');
    });
});
```

And I reverted the `index()` and `read()` methods in the `app/Http/JsonApi/DefaultAuthorizer.php` as follows:

```
class DefaultAuthorizer extends AbstractAuthorizer
{

    /**
     * Authorize a resource index request.
     *
     * @param string $type
     *      the domain record type.
     * @param Request $request
     *      the inbound request.
     * @return void
     * @throws AuthenticationException|AuthorizationException
     *      if the request is not authorized.
     */
    public function index($type, $request)
    {
        // no-op, records are available without signing in.
    }

    ...

    /**
     * Authorize a resource read request.
     *
     * @param object $record
     *      the domain record.
     * @param Request $request
     *      the inbound request.
     * @return void
     * @throws AuthenticationException|AuthorizationException
     *      if the request is not authorized.
     */
    public function read($record, $request)
    {
        // no-op, records are available without signing in.
    }
    ...
}
```

however if I don't send the Bearer token I would receive a `401 Unathenticated` response.
I am not sure I am implementing it correctly as per your suggestion: I would like to use a token for all the actions on the users resource type, apart for read and index (that I would like to use freely without a token sent with the request).

**Comment by lindyhopchris** [comment]
It's because you're using the `auth:api` middleware - that will reject it if you don't send a token.

**Comment by lindyhopchris** [comment]
Generally you want to use the `auth` middleware **or** an authorizer. If you use both, then the authorizer is like an additional step that runs after the middleware. The way Laravel's auth middleware works is it assumes you must be authenticated, i.e. you must have provided a token.

**Comment by itwebdeveloper** [comment]
> 
> 
> It's because you're using the `auth:api` middleware - that will reject it if you don't send a token.

Hi @lindyhopchris ,
thanks for your help and time. Do you think would be possible to selectively disable middleware just for the read and index methods in `routes/api.php`?

**Comment by lindyhopchris** [comment]
There's no need to disable middleware for particular actions, because this fine-grain control over authorization for different actions is exactly what the authorizer implementation is designed to do.

The design of your API means there is not a consistent authorization across all your resources, i.e. the user resource has completely different logic to other resources.

Therefore you'll need to use a user authorizer for the user resource, then use a default authorizer for your other resources.

You could only use the `auth` middleware or a default authorizer for your entire API if the authorization logic was identical across all resources, which is not the case in your design.

So something like this:

```php
JsonApi::register('v1')->routes(function ($api, $router) {
   $api->resource('users'); // will use the user authorizer if it exists.
   $api->resource('posts')->authorizer('default');
   $api->resource('comments')->authorizer('default');
});
```

**Comment by itwebdeveloper** [comment]
Hi @lindyhopchris ,
thanks for your response. I want to try to clarify what I am trying to achieve and why I need it.
Let's say that you have a Laravel application with a CRUD model, e.g. User. Assuming your are trying to register a user the middleware used will be `guest` as you cannot authenticate any user. Once the user is registered the other actions `index`, `show`, `update`, `delete `can be protected by the `auth `middleware (which is able to authenticate the user and check if for example he is the owner of that resource).
In my case I have a first party client ([Which OAuth 2.0 grant should I implement?](https://oauth2.thephpleague.com/authorization-server/which-grant/)), specifically my Front-End, that the user will reach, that will be able to communicate with the API (built with Laravel JSON API and protected by Passport). In particular I am able to use the [Password Grant token](https://laravel.com/docs/master/passport#password-grant-tokens), once an existing users logs in my FE for retrieving an access token for the actions `index`, `read`, `update`, `delete`. However if I want to create a new user, as I cannot identify/authenticate any user (as I was doing with the `guest` middleware), I have two options: 

- to use a [Client credentials grant token](https://laravel.com/docs/master/passport#client-credentials-grant-tokens) (but for some reason after retriving the token I am not authenticated, _I will need more investigation about this to understand if it is Laravel Passport or Laravel JSON API_)
- to disable any middleware (simulating the `guest` middleware).

As the first option is not working I was falling on the second option but it seems I cannot selectively disable the middleware for a particular resource action.
Do you have any suggestion?

**Comment by lindyhopchris** [comment]
Yes, I understand the use case and we have an API that is structured exactly like that.

It is totally possible to do this, and the answer is in my previous comment:

```php
JsonApi::register('v1')->routes(function ($api, $router) {
   $api->resource('users'); // will use the users authorizer if it exists.
   $api->resource('posts')->authorizer('default');
   $api->resource('comments')->authorizer('default');
});
```

Alternatively you could have one default authorizer:

```php
JsonApi::register('v1')->authorizer('default')->routes(function ($api, $router) {
   $api->resource('users');
   $api->resource('posts');
   $api->resource('comments');
});
```

Then in the `index`/`read` methods of the authorizer do a no-op if the arguments given to those methods indicate the request is for your `User` class. Personally I prefer the first of these two options but you can do either depending on your preference.

There is a `$guards` property on the authorizer that you will need to set to ensure you are using the guard for Laravel Passport, as per this section of the docs:
https://laravel-json-api.readthedocs.io/en/latest/basics/security/#available-helpers

To be clear, you **must not** use auth middleware in your scenario. The authorizer is designed to give you complete control over authorization for these kinds of scenarios. It's designed to put all your authorization logic in one place, rather than complex patterns of trying to include/exclude middleware for different actions.

I'm going to close this issue because there are no issues with this package at this point - as the package does not need to disable/enable middleware as it already provides a solution for exactly this scenario (authorizers).

**Comment by mathieufrh** [comment]
Hello,

Do you know if the issue about this part exists ? :

"to use a Client credentials grant token (but for some reason after retriving the token I am not authenticated, I will need more investigation about this to understand if it is Laravel Passport or Laravel JSON API)"

I am using this package to implement an API and I can consume it with Passport using Authorization Code Gant and it works. When using Client Grant I can get an access token but when I use it I receive a 401 Unauthenticated.

**Comment by lindyhopchris** [comment]
@mathieufrh I can't really answer that question, you'd need to debug it in your application. Find out where the `401 Unauthenticated` is being thrown from to start?
