### ISSUE TITLE
Class json-api does not exist

### ISSUE THREAD

**Issue by rekrios** [cloudcreativity/laravel-json-api#367]
Hi. i'm trying upgrade rc2 to 1.1 and all time i seeing message 
"Class json-api does not exist", so Facade can't be loaded
Maybe i should load custom service provider somewhere or i hand't done something at configs? 
P.S. app namespace isnt 'App/', but i changed 'namespace' in the config file
P.P.S. Maybe i should add 'CloudCreativity\LaravelJsonApi\ServiceProvider::class,' to providers ? but didn't see it at the dummy app

**Comment by lindyhopchris** [comment]
Hi! Have no idea why you will be encountering this when no one else has.

Can you share the stack trace for the exception? Otherwise it's impossible for me to work out.

**Comment by lindyhopchris** [comment]
Also it would be worth you re-running package discovery to ensure it completes successfully:

```bash
php artisan package:discover
```

**Comment by rekrios** [comment]
[2019-06-07 11:32:15] local.ERROR: Class json-api does not exist {"exception":"[object] (ReflectionException(code: -1): Class json-api does not exist at /backend/vendor/laravel/framework/src/Illuminate/Container/Container.php:779)
[stacktrace]
#0 /backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('json-api')
#1 /backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\\Container\\Container->build('json-api')
#2 /backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\\Container\\Container->resolve('json-api', Array)
#3 /backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(733): Illuminate\\Container\\Container->make('json-api', Array)
#4 /backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(1222): Illuminate\\Foundation\\Application->make('json-api')
#5 /backend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(161): Illuminate\\Container\\Container->offsetGet('json-api')
#6 /backend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(130): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('json-api')
#7 /backend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#8 ***...***/src/app/Providers/AppServiceProvider.php(42): Illuminate\\Support\\Facades\\Facade::__callStatic('defaultApi', Array)
#9 [internal function]: ***\\**\\Directory\\Providers\\AppServiceProvider->boot()
#10 /backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /backend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(793): Illuminate\\Container\\Container->call(Array)
#15 /backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\\Foundation\\Application->bootProvider(Object(***\\**\\Directory\\Providers\\AppServiceProvider))
#16 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(***\\**\\Directory\\Providers\\AppServiceProvider), 13)
#17 /backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(777): array_walk(Array, Object(Closure))
#18 /backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#19 /backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#20 /backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#21 /backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#22 /backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))

**Comment by lindyhopchris** [comment]
Right well that definitely shouldn't be happening. This package's service provider should be automatically loaded, if the package discovery has run correctly in your app.

Can you confirm whether you have re-run the package discovery command I posted above? When you do, the Laravel JSON API package should be listed in the console output you see.

**Comment by rekrios** [comment]
hm, 
php artisan package:discover
In Container.php line 779:
  Class json-api does not exist

**Comment by lindyhopchris** [comment]
So looks like in your app your package discovery has failed at some point. I've never encountered this scenario.

What exact version of Laravel have you got installed?

The solution at the moment is to comment out the `JsonApi::defaultApi` call in your `AppServiceProvider::boot` method, then run the package discovery, then uncomment that line.

**Comment by lindyhopchris** [comment]
Also can you confirm the exact version of Laravel you are on?

**Comment by rekrios** [comment]
5.8.21

**Comment by lindyhopchris** [comment]
Did the solution above work?

**Comment by rekrios** [comment]
no( i will try to check my dependencies and i'll try laravel 5.7

**Comment by lindyhopchris** [comment]
it should work with Laravel 5.8 as we've got production apps running it with this package.

the key thing to establish is what's in your `bootsrap/cache/providers.php` file, as that should have this package and anything else in there. if this package isn't in there, for some reason that's ended up being inaccurate - which I won't be able to work out why, as it's not to do with this package.

**Comment by rekrios** [comment]
maybe this can't be loaded from composer 
           ``` "providers": [
                "CloudCreativity\\LaravelJsonApi\\ServiceProvider"
            ],```

**Comment by lindyhopchris** [comment]
But if that was the case, it wouldn't be working in all the production apps we've got this package running in! Which is why I'm completely confused about this.

There was a bug early on in the 5.7.x series around package discovery.

I'd suggest deleting the `bootstrap/cache/packages.php` (or whatever that file is called), then `composer require laravel/framework:5.7.*` to pull in the latest version... which will also run a new package discovery.

**Comment by lindyhopchris** [comment]
@rekrios any update on this? did you get it solved?

**Comment by GIANTCRAB** [comment]
This very much looks like a problem I previously had. I remember it was due to some autoloader Laravel cache. Vaguely remembered that I did a composer autoload dump or something.

**Comment by lindyhopchris** [comment]
Ah yes, maybe something like:

```bash
$ composer dump-autoload
$ php artisan package:discover
```

**Comment by lindyhopchris** [comment]
Closing due to inactivity. Feel free to re-open if you're still encountering problems.
