### ISSUE TITLE
Client-generated id?

### ISSUE THREAD

**Issue by llhilton** [cloudcreativity/laravel-json-api#368]
I've looked through the old issues on this topic and haven't found help, so hoping I can get some clarity.

I am trying to create a resource called MoodleUser. This has an id that needs to match the ID from another system. I was under the impression from the docs that I could set the ID for a new MoodleUser in the Adapter using the creating hook, like so:

```
protected function creating(MoodleUser $moodleUser, $resource): void
    {
        $moodleUser->{$moodleUser->getRouteKeyName()} = $resource['lmsUserId'];
    }
```

Using Ember.js, I send the call like so:
```
newMoodleUser = this.store.createRecord('moodle-user', {
        lmsUserId: lmsUser.id,
        institutionId: institution.id,
      });
yield newMoodleUser.save();
```
That gives me a $resource in the creating hook that looks like this:
```
 array (
  'type' => 'moodle-users',
  'attributes' =>
  array (
    'lmsUserId' => '199',
    'institutionId' => '3',
  ),
)
```
Instead of making a new MoodleUser with the id of, say, 199, I get an error that "Id member is an empty string." 

I tried some other things, like passing in an id attribute in the createRecord method, but that gave me a 403 error that client-generated ids weren't supported for the moodle-user resource. 

I'm not sure what else to try or where else to look for assistance. Any help would be most appreciated!

**Comment by lindyhopchris** [comment]
Hi!

If you're trying to use a client generated id then you need to be doing this in Ember:

```js
newMoodleUser = this.store.createRecord('moodle-user', {
        id: lmsUser.id,
        institutionId: institution.id,
      });
yield newMoodleUser.save();
```

Which should give you a resource in PHP looking like this:

```php
 array (
  'type' => 'moodle-users',
  'id' => '199',
  'attributes' =>
  array (
    'institutionId' => '3',
  ),
)
```

To avoid the `403` error, you need to add a validation rule for the `id` - that will enable support for client-generated ids. If you want to enable support but without validating the id (not recommended), then you can do that on your `Validators` class as per this docblock:
https://github.com/cloudcreativity/laravel-json-api/blob/b47b7661195dbd441b6abfe15281aeadce139cc9/src/Validation/AbstractValidators.php#L45-L54

FYI, there's no need to check whether the client-generated id exists as this package takes care of that for you, as we need to do that to check that everything complies with the JSON API spec.

I thought I'd added this to the docs but looking through them I can't find anything about client ids! So I'll leave this issue open as a reminder for me to document it.

**Comment by llhilton** [comment]
Hmm, I updated the front end to your suggestion and added the validation ('id' => 'required_without:institutionId|string',), and now I'm getting the input as you indicated. I've got this in the MoodleUser Adapter:
```
protected function creating(MoodleUser $moodleUser, $resource): void
    {
        $moodleUser->{$moodleUser->getRouteKeyName()} = (string) $resource['id'];
    }
```
But I'm now getting "Id member is an empty string." I tried just doing $moodleUser->id = ... but got the same result. I've logged the $resource['id'] and it's been the correct value. I made id fillable on the MoodleUser model. Not sure what might be interfering here. Anything else I'm missing?

**Comment by lindyhopchris** [comment]
Where are you getting `Id member is an empty string` from? If that's in the response, then you need to inspect the HTTP request body that is being sent. I am an Ember developer but for the purposes of this package it's irrelevant what is being used no the client side... I'd suggest starting with what the actual content of the HTTP request is.

As a side note, if the institution is a `belongsTo` relationship in Ember, your JS code should probably look something like this:

```js
this.store.createRecord('moodle-user', {
  id: lmsUser.id,
  institution,
});
```

As Ember Data will take care of the relationship if you pass the actual object in rather than the id.

**Comment by llhilton** [comment]
The error is happening on the back end somewhere, so I get a 500 error. The http request looks exactly as expected, and the $moodleUser variable in the creating method on the adapter looks correct after setting the id as above. But for some reason, I'm getting this:
```

> local.ERROR: Id member is an empty string. {"userId":147,"email":"admin@mosaiclearning.com","exception":"[object] (CloudCreativity\\LaravelJsonApi\\Exceptions\\RuntimeException(code: 0): Id member is an empty string. at /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Object/IdentifiableTrait.php:79)
> [stacktrace]
> #0 /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Object/ResourceIdentifier.php(126): CloudCreativity\\LaravelJsonApi\\Object\\ResourceIdentifier->getId()
> #1 /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Store/IdentityMap.php(103): CloudCreativity\\LaravelJsonApi\\Object\\ResourceIdentifier->toString()
> #2 /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Store/IdentityMap.php(54): CloudCreativity\\LaravelJsonApi\\Store\\IdentityMap->lookup(Object(CloudCreativity\\LaravelJsonApi\\Object\\ResourceIdentifier))
> #3 /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Store/Store.php(92): CloudCreativity\\LaravelJsonApi\\Store\\IdentityMap->add(Object(CloudCreativity\\LaravelJsonApi\\Object\\ResourceIdentifier), Object(App\\MoodleUser))
> #4 /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Http/Controllers/JsonApiController.php(389): CloudCreativity\\LaravelJsonApi\\Store\\Store->createRecord('moodle-users', Array, Object(CloudCreativity\\LaravelJsonApi\\Encoder\\Parameters\\EncodingParameters))
> #5 /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Http/Controllers/JsonApiController.php(116): CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController->doCreate(Object(CloudCreativity\\LaravelJsonApi\\Store\\Store), Object(CloudCreativity\\LaravelJsonApi\\Http\\Requests\\CreateResource))
> #6 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController->CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\{closure}(Object(Illuminate\\Database\\MySqlConnection))
> #7 /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Http/Controllers/JsonApiController.php(529): Illuminate\\Database\\Connection->transaction(Object(Closure))
> #8 /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Http/Controllers/JsonApiController.php(117): CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController->transaction(Object(Closure))
> #9 [internal function]: CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController->create(Object(CloudCreativity\\LaravelJsonApi\\Store\\Store), Object(CloudCreativity\\LaravelJsonApi\\Http\\Requests\\CreateResource), 'moodle-users')
> #10 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
> #11 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('create', Array)
> #12 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController), 'create')
> #13 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
> #14 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
> #15 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #16 /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Http/Middleware/NegotiateContent.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #17 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): CloudCreativity\\LaravelJsonApi\\Http\\Middleware\\NegotiateContent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #18 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #19 /home/vagrant/code/vendor/cloudcreativity/laravel-json-api/src/Http/Middleware/BootJsonApi.php(78): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #20 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): CloudCreativity\\LaravelJsonApi\\Http\\Middleware\\BootJsonApi->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'v1')
> #21 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #22 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #23 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #24 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #25 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #26 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
> #27 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #28 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #29 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
> #30 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #31 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #32 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
> #33 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
> #34 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
> #35 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
> #36 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
> #37 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
> #38 /home/vagrant/code/vendor/barryvdh/laravel-cors/src/HandleCors.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #39 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure)) #40 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #41 /home/vagrant/code/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #42 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #43 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #44 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #45 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #46 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #47 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #48 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #49 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #50 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #51 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #52 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #53 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #54 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #55 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #56 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #57 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
> #58 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
> #59 /home/vagrant/code/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
> #60 {main}
> "}

```

**Comment by lindyhopchris** [comment]
Great that helps.

That error is caused by your `Schema::getId()` method returning an empty value, so you need to check what you've got in that method for the schema that is used for this resource.

**Comment by llhilton** [comment]
I've got this in the Schema:
```
public function getId($resource)
    {
        return (string) $resource->getRouteKey();
    }
```
I've gotten pulled to another project, so I can't play around with that by doing something like $resource->id there. Will update if/when I finally escape this other project. :)

**Comment by lindyhopchris** [comment]
So for some reason that method is returning an empty string.

I'd next suggest that the you debug what the resource id is after this line (when you're next back on it):

```php
$moodleUser->{$moodleUser->getRouteKeyName()} = (string) $resource['id'];
```

If `$resource['id']` is empty, I need to see the full HTTP request body.

**Comment by llhilton** [comment]
It is now filled with 199, and logging the $moodleUser gives ` {"institution_id":3,"id":199,"institution":{"id":3,...`, 

However, in the Schema's getId() function, the $resource->id is 0, rather than the id set in the creating method, even though the creating hook does run. 

In fiddling around, I decided to add `$moodleUser->lmsUserId = (string) $resource['id']` into the creating method, and it seems to have moved everything along, although of course giving an error since that column doesn't exist in the database. Although it doesn't hit the Schema getId() function, which seems a little odd. I wonder if there's something that's messing up because it's just an id and the institution_id. 

I think that's as far as I can take this for now. My boss has given me the okay to actually do this what I deem the "right" way (id, lms_id, and institution_id, where lms_id is the moodleUser id), which should work as smoothly as all the other stuff has with this great addition to Laravel. :)

**Comment by lindyhopchris** [comment]
Not sure I fully understand but glad you've found a way forward! There is definitely something odd going on, but it sounds like it's application specific - not least because creating with a client generated ID is tested in this package and works fine in the production apps we're using it in.

I'll leave this issue open as a reminder to add some docs about client generated ids.

**Comment by defunctl** [comment]
I just ran into this, and the issue is the first ID in a legacy database was set to 0, so this was always returning true: https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Object/IdentifiableTrait.php#L78

Fixed it for now by modifying the Schema::getId() method in my resource:

```
	/**
	 * @param $resource
	 *      the domain record being serialized.
	 *
	 * @return string
	 */
	public function getId( $resource ) 
	{
		$id = $resource->getRouteKey();

		if( empty( $id ) ) {
			$id = 1;
		}

		return (string) $id;
	}
```

**Comment by lindyhopchris** [comment]
@defunctl I'd say that's a bug as an id of `"0"` should be ok... I'll create a separate issue for that.
