### ISSUE TITLE
Laravel exceptions are converted to internal server errors

### ISSUE THREAD

**Issue by zarlin** [cloudcreativity/laravel-json-api#570]
I have some logic which checks the database state, and under some conditions I want to throw an exception of a suitable type.

For example: I want to return an error 400 Bad Request to the user with a message about what is wrong.

The docs state:
> This package automatically handles converting common Laravel exceptions to these error objects, for example HTTP exceptions and validation exceptions.

So I throw a BadRequestException, passing my message as a parameter:

```php
use Symfony\Component\HttpFoundation\Exception\BadRequestException;

/**/

throw new BadRequestException("message");
```

However, client-side I receive:

```json
{
	"errors": [
		{
			"status": "500",
			"title": "Internal Server Error"
		}
	]
}
```

Which is the wrong status, and my error message is not included.

Why does this happen?

**Comment by ben221199** [comment]
@zarlin Can you show the content of your Laravel log (located in `./storage/logs/`)?

**Comment by zarlin** [comment]
Here is the log entry from throwing a BadRequestException, including stacktrace.

```
[2020-11-19 17:12:45] local.ERROR: User already has a claim {"userId":1,"exception":"[object] (Symfony\\Component\\HttpFoundation\\Exception\\BadRequestException(code: 0): User already has a claim at D:\\project\\app\\JsonAPI\\v1\\Claims\\Adapter.php:64)
[stacktrace]
#0 D:\\project\\vendor\\cloudcreativity\\laravel-json-api\\src\\Adapter\\AbstractResourceAdapter.php(92): App\\JsonAPI\\v1\\Claims\\Adapter->createRecord(Object(CloudCreativity\\LaravelJsonApi\\Document\\ResourceObject))
#1 D:\\project\\vendor\\cloudcreativity\\laravel-json-api\\src\\Store\\Store.php(83): CloudCreativity\\LaravelJsonApi\\Adapter\\AbstractResourceAdapter->create(Array, Object(CloudCreativity\\LaravelJsonApi\\Encoder\\Parameters\\EncodingParameters))
#2 D:\\project\\vendor\\cloudcreativity\\laravel-json-api\\src\\Http\\Controllers\\JsonApiController.php(437): CloudCreativity\\LaravelJsonApi\\Store\\Store->createRecord('claims', Array, Object(CloudCreativity\\LaravelJsonApi\\Encoder\\Parameters\\EncodingParameters))
#3 D:\\project\\vendor\\cloudcreativity\\laravel-json-api\\src\\Http\\Controllers\\JsonApiController.php(130): CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController->doCreate(Object(CloudCreativity\\LaravelJsonApi\\Store\\Store), Object(CloudCreativity\\LaravelJsonApi\\Http\\Requests\\CreateResource))
#4 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(28): CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController->CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\{closure}(Object(Illuminate\\Database\\MySqlConnection))
#5 D:\\project\\vendor\\cloudcreativity\\laravel-json-api\\src\\Http\\Controllers\\JsonApiController.php(578): Illuminate\\Database\\Connection->transaction(Object(Closure))
#6 D:\\project\\vendor\\cloudcreativity\\laravel-json-api\\src\\Http\\Controllers\\JsonApiController.php(131): CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController->transaction(Object(Closure))
#7 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController->create(Object(CloudCreativity\\LaravelJsonApi\\Store\\Store), Object(CloudCreativity\\LaravelJsonApi\\Http\\Requests\\CreateResource), 'claims')
#8 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('create', Array)
#9 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(255): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController), 'create')
#10 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
#11 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(691): Illuminate\\Routing\\Route->run()
#12 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 D:\\project\\vendor\\cloudcreativity\\laravel-json-api\\src\\Http\\Middleware\\Authorize.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): CloudCreativity\\LaravelJsonApi\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), Object(App\\JsonAPI\\v1\\CurrentUserAuthorizer))
#15 D:\\project\\vendor\\cloudcreativity\\laravel-json-api\\src\\Http\\Middleware\\NegotiateContent.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): CloudCreativity\\LaravelJsonApi\\Http\\Middleware\\NegotiateContent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 D:\\project\\vendor\\cloudcreativity\\laravel-json-api\\src\\Http\\Middleware\\BootJsonApi.php(82): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): CloudCreativity\\LaravelJsonApi\\Http\\Middleware\\BootJsonApi->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'v1')
#19 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
#23 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Illuminate\\Http\\Request), Object(Closure), 'api', Object(Closure))
#24 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#25 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#27 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(693): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#30 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(634): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#31 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#32 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#33 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#34 D:\\project\\vendor\\laravel\\vapor-core\\src\\Http\\Middleware\\ServeStaticAssets.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Vapor\\Http\\Middleware\\ServeStaticAssets->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 D:\\project\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 D:\\project\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#50 D:\\project\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#51 D:\\project\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#52 {main}
"} 
```

**Comment by ben221199** [comment]
Ah okay, can you also show your code at `App\Exceptions\Handler.php`?

**Comment by zarlin** [comment]
Thanks for the quick repsonse! Here is the code:

```php
<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use CloudCreativity\LaravelJsonApi\Exceptions\HandlesErrors;
use Neomerx\JsonApi\Exceptions\JsonApiException;
use Throwable;

class Handler extends ExceptionHandler
{
	use HandlesErrors;

	/**
	 * A list of the exception types that are not reported.
	 *
	 * @var array
	 */
	protected $dontReport = [
		//
		JsonApiException::class,
	];

	/**
	 * A list of the inputs that are never flashed for validation exceptions.
	 *
	 * @var array
	 */
	protected $dontFlash = [
		'password',
		'password_confirmation',
	];

	/**
	 * Register the exception handling callbacks for the application.
	 *
	 * @return void
	 */
	public function register()
	{
		//
	}

	public function render($request, Throwable $exception)
	{
		if ($this->isJsonApi($request, $exception)) {
			return $this->renderJsonApi($request, $exception);
		}

		return parent::render($request, $exception);
	}

	protected function prepareException(Throwable $exception)
	{
		if ($exception instanceof JsonApiException) {
			return $this->prepareJsonApiException($exception);
		}

		return parent::prepareException($exception);
	}
}
```

**Comment by ben221199** [comment]
Hmmm, okay... This is mine:
```PHP
<?php
namespace App\Exceptions;

use CloudCreativity\LaravelJsonApi\Exceptions\HandlesErrors;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Neomerx\JsonApi\Exceptions\JsonApiException;
use Throwable;

class Handler extends ExceptionHandler{

	use HandlesErrors;

	protected $dontReport = [
		JsonApiException::class,
	];

	public function render($request,Throwable $e){
		return $this->renderJsonApi($request,$this->prepareException($e));
	}

	protected function prepareException(Throwable $e){
		$e = parent::prepareException($e);

		if($e instanceof JsonApiException){
			return $this->prepareJsonApiException($e);
		}

		return $e;
	}

}
```

**Comment by zarlin** [comment]
Thanks for sharing your code. Sadly I get the same result with it.

I've stepped through the exception handling code, and the code responsible for the conversion to a `500 Internal Server Error` is found in laravel-json-api's `ExceptionParser.php` class, in the `parse` function:

```php
    public function parse(\Throwable $e): DocumentInterface
    {
        if ($e instanceof JsonApiException) {
            return $e->getErrors();
        }

        if ($e instanceof NeomerxJsonApiException) {
            return NeomerxErrors::cast($e);
        }

        //NOTE: This line fails to extract the message from the exception
        $errors = $this->getErrors($e);

        $document = new NeomerxErrors(...$errors);
        //NOTE: And this line sets the default http code, which turns out to be 500
        $document->setDefaultStatus($this->getDefaultHttpCode($e));

        return $document;
    }
```

The problem with the status code seems to be that in `getDefaultHttpCode`, only a check on `HttpExceptionInterface` is done, while `BadRequestException` only implements `RequestExceptionInterface`

```php
    protected function getDefaultHttpCode(\Throwable $e): ?int
    {
        return ($e instanceof HttpExceptionInterface) ?
            $e->getStatusCode() :
            Response::HTTP_INTERNAL_SERVER_ERROR;
    }
```

Does this mean `BadRequestException` is simply not supported by laravel-json-api?

**Comment by lindyhopchris** [comment]
Hi. So I haven't encountered `BadRequestException` before. It's exceptionally strange that it doesn't implement the HTTP Exception interface! I'll get it added to the exception parser now.

**Comment by lindyhopchris** [comment]
Will be in `3.2.0`. Not sure exactly when I'll tag that as I'm going to look at some other issues first. In the meantime you can install by changing your minimum stability to `dev` and running `composer require cloudcreativity/laravel-json-api:^3.2`

**Comment by zarlin** [comment]
Awesome! Using ^3.2 it works exactly as I would expect! Thank you!

**Comment by lindyhopchris** [comment]
No problem, thanks for reporting!
